
grafana:

  existingSecret: "grafana-admin-creds"

  persistence:
    enabled: true

    type: pvc

    size: 10Gi


prometheus:
  prometheusSpec:

    storageSpec:
      volumeClaimTemplate:
        spec:

          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
  
              storage: 50Gi

alertmanager:
  alertmanagerSpec:

    storage:
      volumeClaimTemplate:
        spec:

          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi