name: Build, Scan, and Deploy to GKE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_GAR_LOCATION: asia-south1
  GKE_CLUSTER: axiler-gke-cluster
  GKE_ZONE: asia-south1-b
  IMAGE_NAME: juice-shop
  HELM_RELEASE_NAME: juiceshop-prod

jobs:
  build-scan-and-push:
    name: "Build, Scan, and Push Image"
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation
      security-events: 'write' # Required to upload SARIF results

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: 'Configure Docker for GAR'
      run: gcloud auth configure-docker ${{ env.GCP_GAR_LOCATION }}-docker.pkg.dev

    - name: 'Build Docker image'
      run: |-
        IMAGE_URI="${{ env.GCP_GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/axiler-docker-repo/${{ env.IMAGE_NAME }}"
        docker build \
          --tag "$IMAGE_URI:${{ github.sha }}" \
          --tag "$IMAGE_URI:latest" \
          .

    - name: 'Scan image with Trivy (Log)'
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.GCP_GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/axiler-docker-repo/${{ env.IMAGE_NAME }}:${{ github.sha }}'
        format: 'table'
        severity: 'HIGH,CRITICAL'
        exit-code: '0' 

    - name: 'Scan image with Trivy (SARIF)'
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.GCP_GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/axiler-docker-repo/${{ env.IMAGE_NAME }}:${{ github.sha }}'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'HIGH,CRITICAL'

    - name: 'Upload Trivy scan results to GitHub Security tab'
      uses: github/codeql-action/upload-sarif@v3
      if: always() # Ensure this runs even if the scan finds issues
      with:
        sarif_file: 'trivy-results.sarif'

    - name: 'Push Docker image to GAR'
      # This step only runs for pushes to the main branch, not for pull requests
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |-
        IMAGE_URI="${{ env.GCP_GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/axiler-docker-repo/${{ env.IMAGE_NAME }}"
        docker push "$IMAGE_URI:${{ github.sha }}"
        docker push "$IMAGE_URI:latest"

  deploy-to-gke:
    name: "Deploy to GKE"
    needs: build-scan-and-push 
    runs-on: ubuntu-latest
    # This job only runs for pushes to the main branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: 'read'
      id-token: 'write' 

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: 'Get GKE cluster credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: 'Deploy with Helm'
      run: |-
        helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ./kubernetes/juice-shop \
          --namespace default \
          --set image.tag=${{ github.sha }} \
          --set image.repository="${{ env.GCP_GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/axiler-docker-repo/${{ env.IMAGE_NAME }}" \
          --wait

    - name: 'Verify deployment'
      run: |-
        echo "Verifying deployment..."
        kubectl get service ${{ env.HELM_RELEASE_NAME }}-juice-shop
        kubectl get pods